# Generated by Django 3.2.18 on 2024-01-29 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ind', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='designation',
            field=models.CharField(default='Default Designation', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='exit', max_length=255),
            preserve_default=False,
        ),
    ]
