# Generated by Django 3.2.18 on 2024-01-31 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ind', '0005_auto_20240131_0804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='member',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='member',
            name='image3',
        ),
    ]
